# より簡単な設定（手動でサービスを作成する場合）
services:
  - type: web
    name: miniapp-backend
    env: ruby
    buildCommand: cd backend && bundle install
    startCommand: cd backend && bundle exec rails server -b 0.0.0.0 -p $PORT

  - type: web
    name: miniapp-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist