services:
  # PostgreSQL Database
  - type: pserv
    name: miniapp-db
    plan: free
    region: oregon

  # Rails Backend API
  - type: web
    name: miniapp-backend
    env: ruby
    region: oregon
    plan: free
    buildCommand: cd backend && bundle install && rails db:migrate
    startCommand: cd backend && bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: miniapp-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        generateValue: true
      - key: SECRET_KEY_BASE
        generateValue: true

  # React Frontend
  - type: web
    name: miniapp-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://miniapp-backend.onrender.com